# Generated by generate.pl from defs.in
package event::names;
use strict;
our @ISA = qw(Exporter);
our @EXPORT = qw(
  %E
  $E_BEGIN
  $E_END
  $E_PROC_INIT
  $E_PROC_DESTROY
  $E_PROC_RESUME_REQ
  $E_PROC_TICK
  $E_WORKER_INIT
  $E_WORKER_DESTROY
  $E_WORKER_NAME
  $E_MODULE_LOAD
  $E_MODULE_UNLOAD
  $E_MODULE_INIT
  $E_FFI_LOAD
  $E_TRACE_FFI
  $E_TRACE_ENTER
  $E_TRACE_LEAVE
  $E_TRACE_ENTER_JMP
  $E_EXCEPTION_HANDLED
  $E_EXCEPTION_UNHANDLED
  $E_GC_BLOCK
  $E_GC_UNBLOCK
  $E_GC_REQ
  $E_GC_MARK_STATS
  $E_GC_SWEEP_STATS
  $E_GC_SWEEP_NOTIFY
  $E_NURSERY_RESIZE
  $E_HEAP_BEFORE_SCAV
  $E_HEAP_AFTER_SCAV
  $E_BLOCK_CHUNK_NEW
  $E_BLOCK_CHUNK_FREE
  $E_HEAP_CHUNK_NEW
  $E_HEAP_CHUNK_FREE
  $E_HEAP_LIMIT
  $E_HEAP_ALLOC_FAILED
  $E_PAR
  $E_STACK_GROW
  $E_STACK_SHRINK
  $E_STACK_TRACE
  $E_STACK_BLACKHOLE
  $E_PROF_TRACE
  $E_PROF_ENABLED
  $E_PROF_DISABLED
  $E_THREAD_NAME
  $E_THREAD_NEW
  $E_THREAD_TERMINATED
  $E_THREAD_BLACKHOLE
  $E_BIGINT_OVERFLOW
  $E_STRBUILDER_OVERFLOW
  $E_TICK
  $E_SIGNAL
  $E_ACTIVITY
  $E_USER
  $E_HEAP_CHECK
  $E_HEAP_DUMP
  $E_HEAP_PROF
  $E_GC_SLICE
  $E_GC_MARKSWEEP
  $E_GC_MARK_PHASE
  $E_GC_MARK_SLICE
  $E_GC_SWEEP_PHASE
  $E_GC_SWEEP_SLICE
  $E_GC_SCAVENGER
  $E_PROC_RUN
  $E_PROC_SUSPEND
  $E_PROC_WAIT_SYNC
  $E_PROC_SYNC
  $E_THREAD_SCHED
  $E_THREAD_RUN
  $E_USER_DURATION
  $E_STARTUP
  $E_SHUTDOWN
  $F_e
  $F_ts
  $F_dur
  $F_dur_wid
  $F_dur_tid
  $F_instant_wid
  $F_instant_tid
  $F_BEGIN_version
  $F_PROC_RESUME_REQ_count
  $F_WORKER_NAME_name
  $F_MODULE_LOAD_module
  $F_MODULE_LOAD_file
  $F_MODULE_LOAD_path
  $F_MODULE_UNLOAD_module
  $F_MODULE_INIT_module
  $F_FFI_LOAD_module
  $F_FFI_LOAD_name
  $F_TRACE_FFI_name
  $F_TRACE_ENTER_module
  $F_TRACE_ENTER_fn
  $F_TRACE_ENTER_file
  $F_TRACE_ENTER_size
  $F_TRACE_ENTER_line
  $F_TRACE_ENTER_interp
  $F_TRACE_LEAVE_module
  $F_TRACE_LEAVE_fn
  $F_TRACE_LEAVE_file
  $F_TRACE_LEAVE_size
  $F_TRACE_LEAVE_line
  $F_TRACE_LEAVE_interp
  $F_TRACE_ENTER_JMP_module
  $F_TRACE_ENTER_JMP_fn
  $F_TRACE_ENTER_JMP_file
  $F_TRACE_ENTER_JMP_size
  $F_TRACE_ENTER_JMP_line
  $F_TRACE_ENTER_JMP_interp
  $F_EXCEPTION_HANDLED_name
  $F_EXCEPTION_HANDLED_trace
  $F_EXCEPTION_UNHANDLED_name
  $F_EXCEPTION_UNHANDLED_trace
  $F_GC_REQ_trigger
  $F_GC_REQ_requestor
  $F_GC_MARK_STATS_object_count
  $F_GC_MARK_STATS_object_words
  $F_GC_MARK_STATS_stack_count
  $F_GC_MARK_STATS_stack_words
  $F_GC_MARK_STATS_collapsed
  $F_GC_SWEEP_STATS_small_live_count
  $F_GC_SWEEP_STATS_small_live_words
  $F_GC_SWEEP_STATS_small_free_count
  $F_GC_SWEEP_STATS_small_free_words
  $F_GC_SWEEP_STATS_medium_live_count
  $F_GC_SWEEP_STATS_medium_live_words
  $F_GC_SWEEP_STATS_medium_free_count
  $F_GC_SWEEP_STATS_medium_free_words
  $F_GC_SWEEP_STATS_large_live_count
  $F_GC_SWEEP_STATS_large_live_words
  $F_GC_SWEEP_STATS_large_free_count
  $F_GC_SWEEP_STATS_large_free_words
  $F_NURSERY_RESIZE_oldLimit
  $F_NURSERY_RESIZE_newLimit
  $F_HEAP_BEFORE_SCAV_major_small_allocSinceSweep
  $F_HEAP_BEFORE_SCAV_major_small_allocSinceStart
  $F_HEAP_BEFORE_SCAV_major_small_totalWords
  $F_HEAP_BEFORE_SCAV_major_medium_allocSinceSweep
  $F_HEAP_BEFORE_SCAV_major_medium_allocSinceStart
  $F_HEAP_BEFORE_SCAV_major_medium_totalWords
  $F_HEAP_BEFORE_SCAV_major_large_allocSinceSweep
  $F_HEAP_BEFORE_SCAV_major_large_allocSinceStart
  $F_HEAP_BEFORE_SCAV_major_large_totalWords
  $F_HEAP_BEFORE_SCAV_minor_usedWords
  $F_HEAP_BEFORE_SCAV_minor_totalWords
  $F_HEAP_BEFORE_SCAV_totalWords
  $F_HEAP_AFTER_SCAV_major_small_allocSinceSweep
  $F_HEAP_AFTER_SCAV_major_small_allocSinceStart
  $F_HEAP_AFTER_SCAV_major_small_totalWords
  $F_HEAP_AFTER_SCAV_major_medium_allocSinceSweep
  $F_HEAP_AFTER_SCAV_major_medium_allocSinceStart
  $F_HEAP_AFTER_SCAV_major_medium_totalWords
  $F_HEAP_AFTER_SCAV_major_large_allocSinceSweep
  $F_HEAP_AFTER_SCAV_major_large_allocSinceStart
  $F_HEAP_AFTER_SCAV_major_large_totalWords
  $F_HEAP_AFTER_SCAV_minor_usedWords
  $F_HEAP_AFTER_SCAV_minor_totalWords
  $F_HEAP_AFTER_SCAV_totalWords
  $F_BLOCK_CHUNK_NEW_heapSize
  $F_BLOCK_CHUNK_NEW_size
  $F_BLOCK_CHUNK_NEW_align
  $F_BLOCK_CHUNK_NEW_start
  $F_BLOCK_CHUNK_FREE_heapSize
  $F_BLOCK_CHUNK_FREE_size
  $F_BLOCK_CHUNK_FREE_align
  $F_BLOCK_CHUNK_FREE_start
  $F_HEAP_CHUNK_NEW_heapSize
  $F_HEAP_CHUNK_NEW_size
  $F_HEAP_CHUNK_NEW_align
  $F_HEAP_CHUNK_NEW_start
  $F_HEAP_CHUNK_FREE_heapSize
  $F_HEAP_CHUNK_FREE_size
  $F_HEAP_CHUNK_FREE_align
  $F_HEAP_CHUNK_FREE_start
  $F_HEAP_LIMIT_limit
  $F_HEAP_LIMIT_heapSize
  $F_HEAP_LIMIT_softLimit
  $F_HEAP_LIMIT_hardLimit
  $F_HEAP_ALLOC_FAILED_type
  $F_HEAP_ALLOC_FAILED_size
  $F_STACK_GROW_reqSize
  $F_STACK_GROW_oldSize
  $F_STACK_GROW_newSize
  $F_STACK_GROW_usedSize
  $F_STACK_SHRINK_reqSize
  $F_STACK_SHRINK_oldSize
  $F_STACK_SHRINK_newSize
  $F_STACK_SHRINK_usedSize
  $F_STACK_TRACE_trace
  $F_STACK_BLACKHOLE_count
  $F_PROF_TRACE_trace
  $F_THREAD_NAME_tid
  $F_THREAD_NAME_name
  $F_THREAD_NEW_tid
  $F_THREAD_NEW_count
  $F_THREAD_TERMINATED_count
  $F_SIGNAL_sig
  $F_ACTIVITY_cpuTimeUser
  $F_ACTIVITY_cpuTimeSystem
  $F_ACTIVITY_residentSize
  $F_ACTIVITY_pageFault
  $F_ACTIVITY_pageSwap
  $F_ACTIVITY_contextSwitch
  $F_ACTIVITY_diskRead
  $F_ACTIVITY_diskWrite
  $F_USER_data
  $F_HEAP_DUMP_file
  $F_HEAP_PROF_array_count
  $F_HEAP_PROF_array_words
  $F_HEAP_PROF_bigint_count
  $F_HEAP_PROF_bigint_words
  $F_HEAP_PROF_box64_count
  $F_HEAP_PROF_box64_words
  $F_HEAP_PROF_buffer_count
  $F_HEAP_PROF_buffer_words
  $F_HEAP_PROF_data_count
  $F_HEAP_PROF_data_words
  $F_HEAP_PROF_ffi_count
  $F_HEAP_PROF_ffi_words
  $F_HEAP_PROF_fn_count
  $F_HEAP_PROF_fn_words
  $F_HEAP_PROF_raw_count
  $F_HEAP_PROF_raw_words
  $F_HEAP_PROF_stack_count
  $F_HEAP_PROF_stack_words
  $F_HEAP_PROF_string_count
  $F_HEAP_PROF_string_words
  $F_HEAP_PROF_stringbuilder_count
  $F_HEAP_PROF_stringbuilder_words
  $F_HEAP_PROF_thread_count
  $F_HEAP_PROF_thread_words
  $F_HEAP_PROF_thunk_count
  $F_HEAP_PROF_thunk_words
  $F_GC_SLICE_trigger
  $F_GC_SCAVENGER_dirty_object_count
  $F_GC_SCAVENGER_dirty_object_words
  $F_GC_SCAVENGER_dirty_stack_count
  $F_GC_SCAVENGER_dirty_stack_words
  $F_GC_SCAVENGER_raw_promoted_count
  $F_GC_SCAVENGER_raw_promoted_words
  $F_GC_SCAVENGER_raw_copied_count
  $F_GC_SCAVENGER_raw_copied_words
  $F_GC_SCAVENGER_object_promoted_count
  $F_GC_SCAVENGER_object_promoted_words
  $F_GC_SCAVENGER_object_copied_count
  $F_GC_SCAVENGER_object_copied_words
  $F_GC_SCAVENGER_object_copied1_count
  $F_GC_SCAVENGER_object_copied1_words
  $F_GC_SCAVENGER_collapsed
  $F_GC_SCAVENGER_gen
  $F_GC_SCAVENGER_snapshot
  $F_USER_DURATION_data
);
our %E = (
  BEGIN => 0,
  END => 1,
  PROC_INIT => 2,
  PROC_DESTROY => 3,
  PROC_RESUME_REQ => 4,
  PROC_TICK => 5,
  WORKER_INIT => 6,
  WORKER_DESTROY => 7,
  WORKER_NAME => 8,
  MODULE_LOAD => 9,
  MODULE_UNLOAD => 10,
  MODULE_INIT => 11,
  FFI_LOAD => 12,
  TRACE_FFI => 13,
  TRACE_ENTER => 14,
  TRACE_LEAVE => 15,
  TRACE_ENTER_JMP => 16,
  EXCEPTION_HANDLED => 17,
  EXCEPTION_UNHANDLED => 18,
  GC_BLOCK => 19,
  GC_UNBLOCK => 20,
  GC_REQ => 21,
  GC_MARK_STATS => 22,
  GC_SWEEP_STATS => 23,
  GC_SWEEP_NOTIFY => 24,
  NURSERY_RESIZE => 25,
  HEAP_BEFORE_SCAV => 26,
  HEAP_AFTER_SCAV => 27,
  BLOCK_CHUNK_NEW => 28,
  BLOCK_CHUNK_FREE => 29,
  HEAP_CHUNK_NEW => 30,
  HEAP_CHUNK_FREE => 31,
  HEAP_LIMIT => 32,
  HEAP_ALLOC_FAILED => 33,
  PAR => 34,
  STACK_GROW => 35,
  STACK_SHRINK => 36,
  STACK_TRACE => 37,
  STACK_BLACKHOLE => 38,
  PROF_TRACE => 39,
  PROF_ENABLED => 40,
  PROF_DISABLED => 41,
  THREAD_NAME => 42,
  THREAD_NEW => 43,
  THREAD_TERMINATED => 44,
  THREAD_BLACKHOLE => 45,
  BIGINT_OVERFLOW => 46,
  STRBUILDER_OVERFLOW => 47,
  TICK => 48,
  SIGNAL => 49,
  ACTIVITY => 50,
  USER => 51,
  HEAP_CHECK => 53,
  HEAP_DUMP => 55,
  HEAP_PROF => 57,
  GC_SLICE => 59,
  GC_MARKSWEEP => 61,
  GC_MARK_PHASE => 63,
  GC_MARK_SLICE => 65,
  GC_SWEEP_PHASE => 67,
  GC_SWEEP_SLICE => 69,
  GC_SCAVENGER => 71,
  PROC_RUN => 73,
  PROC_SUSPEND => 75,
  PROC_WAIT_SYNC => 77,
  PROC_SYNC => 79,
  THREAD_SCHED => 81,
  THREAD_RUN => 83,
  USER_DURATION => 85,
  STARTUP => 87,
  SHUTDOWN => 89
);
our $E_BEGIN = 0;
our $E_END = 1;
our $E_PROC_INIT = 2;
our $E_PROC_DESTROY = 3;
our $E_PROC_RESUME_REQ = 4;
our $E_PROC_TICK = 5;
our $E_WORKER_INIT = 6;
our $E_WORKER_DESTROY = 7;
our $E_WORKER_NAME = 8;
our $E_MODULE_LOAD = 9;
our $E_MODULE_UNLOAD = 10;
our $E_MODULE_INIT = 11;
our $E_FFI_LOAD = 12;
our $E_TRACE_FFI = 13;
our $E_TRACE_ENTER = 14;
our $E_TRACE_LEAVE = 15;
our $E_TRACE_ENTER_JMP = 16;
our $E_EXCEPTION_HANDLED = 17;
our $E_EXCEPTION_UNHANDLED = 18;
our $E_GC_BLOCK = 19;
our $E_GC_UNBLOCK = 20;
our $E_GC_REQ = 21;
our $E_GC_MARK_STATS = 22;
our $E_GC_SWEEP_STATS = 23;
our $E_GC_SWEEP_NOTIFY = 24;
our $E_NURSERY_RESIZE = 25;
our $E_HEAP_BEFORE_SCAV = 26;
our $E_HEAP_AFTER_SCAV = 27;
our $E_BLOCK_CHUNK_NEW = 28;
our $E_BLOCK_CHUNK_FREE = 29;
our $E_HEAP_CHUNK_NEW = 30;
our $E_HEAP_CHUNK_FREE = 31;
our $E_HEAP_LIMIT = 32;
our $E_HEAP_ALLOC_FAILED = 33;
our $E_PAR = 34;
our $E_STACK_GROW = 35;
our $E_STACK_SHRINK = 36;
our $E_STACK_TRACE = 37;
our $E_STACK_BLACKHOLE = 38;
our $E_PROF_TRACE = 39;
our $E_PROF_ENABLED = 40;
our $E_PROF_DISABLED = 41;
our $E_THREAD_NAME = 42;
our $E_THREAD_NEW = 43;
our $E_THREAD_TERMINATED = 44;
our $E_THREAD_BLACKHOLE = 45;
our $E_BIGINT_OVERFLOW = 46;
our $E_STRBUILDER_OVERFLOW = 47;
our $E_TICK = 48;
our $E_SIGNAL = 49;
our $E_ACTIVITY = 50;
our $E_USER = 51;
our $E_HEAP_CHECK = 53;
our $E_HEAP_DUMP = 55;
our $E_HEAP_PROF = 57;
our $E_GC_SLICE = 59;
our $E_GC_MARKSWEEP = 61;
our $E_GC_MARK_PHASE = 63;
our $E_GC_MARK_SLICE = 65;
our $E_GC_SWEEP_PHASE = 67;
our $E_GC_SWEEP_SLICE = 69;
our $E_GC_SCAVENGER = 71;
our $E_PROC_RUN = 73;
our $E_PROC_SUSPEND = 75;
our $E_PROC_WAIT_SYNC = 77;
our $E_PROC_SYNC = 79;
our $E_THREAD_SCHED = 81;
our $E_THREAD_RUN = 83;
our $E_USER_DURATION = 85;
our $E_STARTUP = 87;
our $E_SHUTDOWN = 89;
our $F_e = 0;
our $F_ts = 1;
our $F_dur = 2;
our $F_dur_wid = 3;
our $F_dur_tid = 4;
our $F_instant_wid = 2;
our $F_instant_tid = 3;
our $F_BEGIN_version = 2;
our $F_PROC_RESUME_REQ_count = 4;
our $F_WORKER_NAME_name = 3;
our $F_MODULE_LOAD_module = 3;
our $F_MODULE_LOAD_file = 4;
our $F_MODULE_LOAD_path = 5;
our $F_MODULE_UNLOAD_module = 3;
our $F_MODULE_INIT_module = 3;
our $F_FFI_LOAD_module = 3;
our $F_FFI_LOAD_name = 4;
our $F_TRACE_FFI_name = 4;
our $F_TRACE_ENTER_module = 4;
our $F_TRACE_ENTER_fn = 5;
our $F_TRACE_ENTER_file = 6;
our $F_TRACE_ENTER_size = 7;
our $F_TRACE_ENTER_line = 8;
our $F_TRACE_ENTER_interp = 9;
our $F_TRACE_LEAVE_module = 4;
our $F_TRACE_LEAVE_fn = 5;
our $F_TRACE_LEAVE_file = 6;
our $F_TRACE_LEAVE_size = 7;
our $F_TRACE_LEAVE_line = 8;
our $F_TRACE_LEAVE_interp = 9;
our $F_TRACE_ENTER_JMP_module = 4;
our $F_TRACE_ENTER_JMP_fn = 5;
our $F_TRACE_ENTER_JMP_file = 6;
our $F_TRACE_ENTER_JMP_size = 7;
our $F_TRACE_ENTER_JMP_line = 8;
our $F_TRACE_ENTER_JMP_interp = 9;
our $F_EXCEPTION_HANDLED_name = 4;
our $F_EXCEPTION_HANDLED_trace = 5;
our $F_EXCEPTION_UNHANDLED_name = 4;
our $F_EXCEPTION_UNHANDLED_trace = 5;
our $F_GC_REQ_trigger = 2;
our $F_GC_REQ_requestor = 3;
our $F_GC_MARK_STATS_object_count = 3;
our $F_GC_MARK_STATS_object_words = 4;
our $F_GC_MARK_STATS_stack_count = 5;
our $F_GC_MARK_STATS_stack_words = 6;
our $F_GC_MARK_STATS_collapsed = 7;
our $F_GC_SWEEP_STATS_small_live_count = 3;
our $F_GC_SWEEP_STATS_small_live_words = 4;
our $F_GC_SWEEP_STATS_small_free_count = 5;
our $F_GC_SWEEP_STATS_small_free_words = 6;
our $F_GC_SWEEP_STATS_medium_live_count = 7;
our $F_GC_SWEEP_STATS_medium_live_words = 8;
our $F_GC_SWEEP_STATS_medium_free_count = 9;
our $F_GC_SWEEP_STATS_medium_free_words = 10;
our $F_GC_SWEEP_STATS_large_live_count = 11;
our $F_GC_SWEEP_STATS_large_live_words = 12;
our $F_GC_SWEEP_STATS_large_free_count = 13;
our $F_GC_SWEEP_STATS_large_free_words = 14;
our $F_NURSERY_RESIZE_oldLimit = 3;
our $F_NURSERY_RESIZE_newLimit = 4;
our $F_HEAP_BEFORE_SCAV_major_small_allocSinceSweep = 3;
our $F_HEAP_BEFORE_SCAV_major_small_allocSinceStart = 4;
our $F_HEAP_BEFORE_SCAV_major_small_totalWords = 5;
our $F_HEAP_BEFORE_SCAV_major_medium_allocSinceSweep = 6;
our $F_HEAP_BEFORE_SCAV_major_medium_allocSinceStart = 7;
our $F_HEAP_BEFORE_SCAV_major_medium_totalWords = 8;
our $F_HEAP_BEFORE_SCAV_major_large_allocSinceSweep = 9;
our $F_HEAP_BEFORE_SCAV_major_large_allocSinceStart = 10;
our $F_HEAP_BEFORE_SCAV_major_large_totalWords = 11;
our $F_HEAP_BEFORE_SCAV_minor_usedWords = 12;
our $F_HEAP_BEFORE_SCAV_minor_totalWords = 13;
our $F_HEAP_BEFORE_SCAV_totalWords = 14;
our $F_HEAP_AFTER_SCAV_major_small_allocSinceSweep = 3;
our $F_HEAP_AFTER_SCAV_major_small_allocSinceStart = 4;
our $F_HEAP_AFTER_SCAV_major_small_totalWords = 5;
our $F_HEAP_AFTER_SCAV_major_medium_allocSinceSweep = 6;
our $F_HEAP_AFTER_SCAV_major_medium_allocSinceStart = 7;
our $F_HEAP_AFTER_SCAV_major_medium_totalWords = 8;
our $F_HEAP_AFTER_SCAV_major_large_allocSinceSweep = 9;
our $F_HEAP_AFTER_SCAV_major_large_allocSinceStart = 10;
our $F_HEAP_AFTER_SCAV_major_large_totalWords = 11;
our $F_HEAP_AFTER_SCAV_minor_usedWords = 12;
our $F_HEAP_AFTER_SCAV_minor_totalWords = 13;
our $F_HEAP_AFTER_SCAV_totalWords = 14;
our $F_BLOCK_CHUNK_NEW_heapSize = 2;
our $F_BLOCK_CHUNK_NEW_size = 3;
our $F_BLOCK_CHUNK_NEW_align = 4;
our $F_BLOCK_CHUNK_NEW_start = 5;
our $F_BLOCK_CHUNK_FREE_heapSize = 2;
our $F_BLOCK_CHUNK_FREE_size = 3;
our $F_BLOCK_CHUNK_FREE_align = 4;
our $F_BLOCK_CHUNK_FREE_start = 5;
our $F_HEAP_CHUNK_NEW_heapSize = 2;
our $F_HEAP_CHUNK_NEW_size = 3;
our $F_HEAP_CHUNK_NEW_align = 4;
our $F_HEAP_CHUNK_NEW_start = 5;
our $F_HEAP_CHUNK_FREE_heapSize = 2;
our $F_HEAP_CHUNK_FREE_size = 3;
our $F_HEAP_CHUNK_FREE_align = 4;
our $F_HEAP_CHUNK_FREE_start = 5;
our $F_HEAP_LIMIT_limit = 2;
our $F_HEAP_LIMIT_heapSize = 3;
our $F_HEAP_LIMIT_softLimit = 4;
our $F_HEAP_LIMIT_hardLimit = 5;
our $F_HEAP_ALLOC_FAILED_type = 4;
our $F_HEAP_ALLOC_FAILED_size = 5;
our $F_STACK_GROW_reqSize = 4;
our $F_STACK_GROW_oldSize = 5;
our $F_STACK_GROW_newSize = 6;
our $F_STACK_GROW_usedSize = 7;
our $F_STACK_SHRINK_reqSize = 4;
our $F_STACK_SHRINK_oldSize = 5;
our $F_STACK_SHRINK_newSize = 6;
our $F_STACK_SHRINK_usedSize = 7;
our $F_STACK_TRACE_trace = 4;
our $F_STACK_BLACKHOLE_count = 4;
our $F_PROF_TRACE_trace = 3;
our $F_THREAD_NAME_tid = 3;
our $F_THREAD_NAME_name = 4;
our $F_THREAD_NEW_tid = 4;
our $F_THREAD_NEW_count = 5;
our $F_THREAD_TERMINATED_count = 4;
our $F_SIGNAL_sig = 2;
our $F_ACTIVITY_cpuTimeUser = 2;
our $F_ACTIVITY_cpuTimeSystem = 3;
our $F_ACTIVITY_residentSize = 4;
our $F_ACTIVITY_pageFault = 5;
our $F_ACTIVITY_pageSwap = 6;
our $F_ACTIVITY_contextSwitch = 7;
our $F_ACTIVITY_diskRead = 8;
our $F_ACTIVITY_diskWrite = 9;
our $F_USER_data = 4;
our $F_HEAP_DUMP_file = 4;
our $F_HEAP_PROF_array_count = 4;
our $F_HEAP_PROF_array_words = 5;
our $F_HEAP_PROF_bigint_count = 6;
our $F_HEAP_PROF_bigint_words = 7;
our $F_HEAP_PROF_box64_count = 8;
our $F_HEAP_PROF_box64_words = 9;
our $F_HEAP_PROF_buffer_count = 10;
our $F_HEAP_PROF_buffer_words = 11;
our $F_HEAP_PROF_data_count = 12;
our $F_HEAP_PROF_data_words = 13;
our $F_HEAP_PROF_ffi_count = 14;
our $F_HEAP_PROF_ffi_words = 15;
our $F_HEAP_PROF_fn_count = 16;
our $F_HEAP_PROF_fn_words = 17;
our $F_HEAP_PROF_raw_count = 18;
our $F_HEAP_PROF_raw_words = 19;
our $F_HEAP_PROF_stack_count = 20;
our $F_HEAP_PROF_stack_words = 21;
our $F_HEAP_PROF_string_count = 22;
our $F_HEAP_PROF_string_words = 23;
our $F_HEAP_PROF_stringbuilder_count = 24;
our $F_HEAP_PROF_stringbuilder_words = 25;
our $F_HEAP_PROF_thread_count = 26;
our $F_HEAP_PROF_thread_words = 27;
our $F_HEAP_PROF_thunk_count = 28;
our $F_HEAP_PROF_thunk_words = 29;
our $F_GC_SLICE_trigger = 4;
our $F_GC_SCAVENGER_dirty_object_count = 4;
our $F_GC_SCAVENGER_dirty_object_words = 5;
our $F_GC_SCAVENGER_dirty_stack_count = 6;
our $F_GC_SCAVENGER_dirty_stack_words = 7;
our $F_GC_SCAVENGER_raw_promoted_count = 8;
our $F_GC_SCAVENGER_raw_promoted_words = 9;
our $F_GC_SCAVENGER_raw_copied_count = 10;
our $F_GC_SCAVENGER_raw_copied_words = 11;
our $F_GC_SCAVENGER_object_promoted_count = 12;
our $F_GC_SCAVENGER_object_promoted_words = 13;
our $F_GC_SCAVENGER_object_copied_count = 14;
our $F_GC_SCAVENGER_object_copied_words = 15;
our $F_GC_SCAVENGER_object_copied1_count = 16;
our $F_GC_SCAVENGER_object_copied1_words = 17;
our $F_GC_SCAVENGER_collapsed = 18;
our $F_GC_SCAVENGER_gen = 19;
our $F_GC_SCAVENGER_snapshot = 20;
our $F_USER_DURATION_data = 5;
1;
