#undef XFORMAT
#undef XSTR
#undef XBLOCK_BEGIN
#undef XUBLOCK_BEGIN
#undef XBLOCK_END
#undef XUBLOCK_END
#undef XFIELD
#undef XINIT
#undef XINIT
#undef XEVENT_BEGIN
#undef XEVENT_END
#undef XSTATE
#undef XNUM
#undef XSNUM
#undef XENUM
