#include "release.h"

#undef  CHI_PROF_ENABLED
#define CHI_PROF_ENABLED 1

#undef  CHI_TRACEPOINTS_ENABLED
#define CHI_TRACEPOINTS_ENABLED 1

#undef  CHI_TRACEPOINTS_CONT_ENABLED
#define CHI_TRACEPOINTS_CONT_ENABLED 1
