#include "release.h"

#undef CHI_LOC_ENABLED
#define CHI_LOC_ENABLED 0

#undef CHI_COLOR_ENABLED
#define CHI_COLOR_ENABLED 0

#undef CHI_STATS_ENABLED
#define CHI_STATS_ENABLED 0

#undef CHI_STATS_SCAV_ENABLED
#define CHI_STATS_SCAV_ENABLED 0

#undef CHI_STATS_MARK_ENABLED
#define CHI_STATS_MARK_ENABLED 0

#undef CHI_STATS_SWEEP_ENABLED
#define CHI_STATS_SWEEP_ENABLED 0

#undef CHI_EVENT_ENABLED
#define CHI_EVENT_ENABLED 0

#undef CHI_HEAP_CHECK_ENABLED
#define CHI_HEAP_CHECK_ENABLED 0

#undef CHI_HEAP_DUMP_ENABLED
#define CHI_HEAP_DUMP_ENABLED 0

#undef CHI_HEAP_PROF_ENABLED
#define CHI_HEAP_PROF_ENABLED 0

#undef CHI_DTRACE_ENABLED
#define CHI_DTRACE_ENABLED 0

#undef CHI_HEAPTRACK_ENABLED
#define CHI_HEAPTRACK_ENABLED 0

#undef CHI_VALGRIND_ENABLED
#define CHI_VALGRIND_ENABLED 0

#undef CHI_PAGER_ENABLED
#define CHI_PAGER_ENABLED 0

#undef CBY_BACKEND_TRACE_ENABLED
#define CBY_BACKEND_TRACE_ENABLED 0

#undef CBY_BACKEND_DUMP_ENABLED
#define CBY_BACKEND_DUMP_ENABLED 0

#undef CBY_BACKEND_CYCLES_ENABLED
#define CBY_BACKEND_CYCLES_ENABLED 0

#undef CBY_BACKEND_COUNT_ENABLED
#define CBY_BACKEND_COUNT_ENABLED 0

#undef CBY_BACKEND_CALLS_ENABLED
#define CBY_BACKEND_CALLS_ENABLED 0

#undef CBY_BACKEND_PROF_ENABLED
#define CBY_BACKEND_PROF_ENABLED 0

#undef CBY_DISASM_ENABLED
#define CBY_DISASM_ENABLED 0

#undef CBY_LSMOD_ENABLED
#define CBY_LSMOD_ENABLED 0
