#!/bin/bash
(
    echo "// Generated by private.sh"
    echo "#include \"private_macros.h\""
    (
        for i in $(grep -hoPr '(?<=CHI_PRIVATE\()\w\w+(?=\))' $(dirname "$0")/include); do
            echo "#define $i _$i"
        done
        for i in $(grep -hoPr '(?<=^CHI_OBJECT\()[^)]*' $(dirname "$0") | sed 's/[^,]*,//;s/,.*//'); do
            echo "#define chiTo$i _chiTo$i"
        done
    ) | sort | uniq
) > $(dirname "$0")/private.h
