#undef INSTRUMENT_NAME
#undef INTERP_DISPATCH
#undef INTERP_NAME
#undef InstrumentData
#undef InterpPS
#undef InterpState
#undef instrumentAlloc
#undef instrumentDestroy
#undef instrumentEnter
#undef instrumentFFITail
#undef instrumentFFIBegin
#undef instrumentFFIEnd
#undef instrumentInsnBegin
#undef instrumentInsnEnd
#undef instrumentLeave
#undef instrumentProcStart
#undef instrumentProcStop
#undef instrumentSetup
#undef interpBackend
#undef interpCont
#undef interpFn
#undef interpGetPS
#undef interpGetState
#undef interpProcStart
#undef interpProcStop
#undef interpSetup
#undef interpreter
#undef DISPATCH_BEGIN
#undef DISPATCH_END
#undef DISPATCH_PROLOGUE
#undef DISPATCH_INIT
#undef DISPATCH_REWRITE
#undef DISPATCH_JUMP
